export const CHOOSE_CARD = "CHOOSE_CARD";
export const NEW_GAME = "NEW_GAME";
export const CHANGE_DIFFICULTY = "CHANGE_DIFFICULTY";
export const CHANGE_COLLECTION = "CHANGE_COLLECTION";
export const REFRESH_VIEW = "REFRESH_VIEW";
